In [23]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import np_utils
import numpy as np

In [24]:
seed = 7
np.random.seed(seed)
data = np.loadtxt("data.txt")
X_train = data[:4646,:12]
Y_train = data[:4646,12:13]
X_test = data[4646:6936,:12]
Y_test = data[4646:6936,12:13]
len_y_train = len(Y_train)
len_y_test = len(Y_test)
print(len(Y_train))
print(len(Y_test))

4646
2289


In [25]:
for i in range(0,len_y_train):
    if(Y_train[i]==1000):
        Y_train[i] = 3
        Y_train[i] = int(Y_train[i])
    elif(Y_train[i]==100):
        Y_train[i] = 2
        Y_train[i] = int(Y_train[i])
    elif(Y_train[i]==10):
        Y_train[i] = 1
        Y_train[i] = int(Y_train[i])
    elif(Y_train[i]==1):
        Y_train[i] = 0
        Y_train[i] = int(Y_train[i])

for i in range(0,len_y_test):
    if(Y_test[i]==1000):
        Y_test[i] = 3
        Y_test[i] = int(Y_test[i])
    elif(Y_test[i]==100):
        Y_test[i] = 2
        Y_test[i] = int(Y_test[i])
    elif(Y_test[i]==10):
        Y_test[i] = 1
        Y_test[i] = int(Y_test[i])
    elif(Y_test[i]==1):
        Y_test[i] = 0
        Y_test[i] = int(Y_test[i])

print(Y_train)
print(Y_test)

[[2.]
 [2.]
 [2.]
 ...
 [3.]
 [3.]
 [3.]]
[[3.]
 [3.]
 [3.]
 ...
 [2.]
 [2.]
 [2.]]


In [ ]:
Y_train = Y_train.astype('int32')
Y_train = np_utils.to_categorical(Y_train,4)
Y_test = Y_test.astype('int32')
Y_test = np_utils.to_categorical(Y_test,4)
model = Sequential()
model.add(Dense(100, input_dim=12, init='uniform', activation='relu'))
model.add(Dense(80, init='uniform', activation='relu'))
model.add(Dense(60, init='uniform', activation='relu'))
model.add(Dense(60, init='uniform', activation='relu'))
model.add(Dense(4))
model.add(Activation('softmax'))
model.summary()
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train, nb_epoch=50, batch_size=10, verbose=2, validation_data=(X_test,Y_test))
scores = model.evaluate(X_test, Y_test, verbose=0)
print("\n")
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

C:\Users\welcome\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(100, input_dim=12, activation="relu", kernel_initializer="uniform")`
  
C:\Users\welcome\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(80, activation="relu", kernel_initializer="uniform")`
  import sys
C:\Users\welcome\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(60, activation="relu", kernel_initializer="uniform")`
  
C:\Users\welcome\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(60, activation="relu", kernel_initializer="uniform")`
  if __name__ == '__main__':
C:\Users\welcome\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_26 (Dense)             (None, 100)               1300      
_________________________________________________________________
dense_27 (Dense)             (None, 80)                8080      
_________________________________________________________________
dense_28 (Dense)             (None, 60)                4860      
_________________________________________________________________
dense_29 (Dense)             (None, 60)                3660      
_________________________________________________________________
dense_30 (Dense)             (None, 4)                 244       
_________________________________________________________________
activation_6 (Activation)    (None, 4)                 0         
Total params: 18,144
Trainable params: 18,144
Non-trainable params: 0
_________________________________________________________________
Train 

In [7]:
pre_data = np.loadtxt('predict.txt')
model = open('model.g').read()
model.load_weights('weight.h5')
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
pre_data = pre_data.astype('int32')
pre_data = pre_data.reshape(1,12)
print(pre_data)

[[   0   22   10   13    9  101   47 1021 1017    3    1   15]]


In [15]:
ans = model.predict(x=pre_data)
print('\n',ans)


 [[0.01250363 0.02864366 0.91477937 0.04407343]]
